apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    com.xebialabs.service: invoice-app
  name: invoice-app
spec:
  replicas: 1
  selector:
    com.xebialabs.service: invoice-app
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        com.xebialabs.service: invoice-app
    spec:
      containers:
      - env:
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://admin:admin@jhipster-registry:8761/eureka
        - name: JHIPSTER_REGISTRY_PASSWORD
          value: admin
        - name: JHIPSTER_SLEEP
          value: "10"
        - name: HOME
          value: "/home/jhipster"
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://admin:admin@jhipster-registry:8761/config
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://invoice-mysql:3306/invoice?useUnicode=true&characterEncoding=utf8&useSSL=false
        - name: SPRING_PROFILES_ACTIVE
          value: prod,swagger
        image: ' '
        name: invoice-app
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - invoice-app
      from:
        kind: ImageStreamTag
        name: invoice-app:latest
    type: ImageChange