resources:
  # Common 
  - common-daemonset.yaml
  # Store Application
  - store/store-app-deploymentconfig.yaml
  - store/store-app-imagestream.yaml
  - store/store-app-service.yaml
  - store/store-app-route.yaml
  # Store Database
  - store/store-mysql-claim0-persistentvolumeclaim.yaml
  - store/store-mysql-deploymentconfig.yaml
  - store/store-mysql-service.yaml  
  # Invoice Application
  - invoice/invoice-app-deploymentconfig.yaml
  - invoice/invoice-app-imagestream.yaml
  - invoice/invoice-app-service.yaml
  # Invoice Database
  - invoice/invoice-mysql-claim0-persistentvolumeclaim.yaml
  - invoice/invoice-mysql-deploymentconfig.yaml
  - invoice/invoice-mysql-service.yaml
  # Notification Application
  - notification/notification-app-deploymentconfig.yaml
  - notification/notification-app-imagestream.yaml
  - notification/notification-app-service.yaml
  # Notification Database
  - notification/notification-mongodb-claim0-persistentvolumeclaim.yaml
  - notification/notification-mongodb-deploymentconfig.yaml
  - notification/notification-mongodb-imagestream.yaml
  - notification/notification-mongodb-service.yaml  
  # JHipster Registry
  - jhipster-registry/jhipster-registry-claim0-persistentvolumeclaim.yaml
  - jhipster-registry/jhipster-registry-configmap.yaml
  - jhipster-registry/jhipster-registry-statefulset.yaml
  - jhipster-registry/jhipster-registry-imagestream.yaml
  - jhipster-registry/jhipster-registry-service.yaml  
  - jhipster-registry/jhipster-registry-route.yaml
  - jhipster-registry/jhipster-registry-secrets.yaml
  # JHipster logstash
  - console/jhipster-logstash-deploymentconfig.yaml
  - console/jhipster-logstash-service.yaml
  - console/jhipster-logstash-configmap.yaml
  # JHipster Console
  - jhipster-console/jhipster-console-deploymentconfig.yaml
  - jhipster-console/jhipster-console-imagestream.yaml
  - jhipster-console/jhipster-console-service.yaml
  - jhipster-console/jhipster-console-route.yaml
  # JHipster elasticsearch
  - jhipster-elasticsearch/jhipster-elasticsearch-client-deploymentconfig.yaml
  - jhipster-elasticsearch/jhipster-elasticsearch-service.yaml
  - jhipster-elasticsearch/jhipster-elasticsearch-discovery-service.yaml
  - jhipster-elasticsearch/jhipster-elasticsearch-data-service.yaml
  - jhipster-elasticsearch/jhipster-elasticsearch-configmap.yaml
  - jhipster-elasticsearch/jhipster-elasticsearch-master-statefulset.yaml
  - jhipster-elasticsearch/jhipster-elasticsearch-data-statefulset.yaml
  # JHipster import Job
  - jhipster-console/jhipster-console-dashboard-job.yaml
  # jhipster-zipkin
  - jhipster-zipkin/jhipster-zipkin-deploymentconfig.yaml
  - jhipster-zipkin/jhipster-zipkin-service.yaml
