resources:
  # Store Application
  - store-app-deploymentconfig.yaml
  - store-app-imagestream.yaml
  - store-app-service.yaml
  - store-app-route.yaml
  # Store Database
  - store-mysql-claim0-persistentvolumeclaim.yaml
  - store-mysql-deploymentconfig.yaml
  - store-mysql-imagestream.yaml
  - store-mysql-service.yaml  
  # Invoice Application
  - invoice-app-deploymentconfig.yaml
  - invoice-app-imagestream.yaml
  - invoice-app-service.yaml
  # Invoice Database
  - invoice-mysql-claim0-persistentvolumeclaim.yaml
  - invoice-mysql-deploymentconfig.yaml
  - invoice-mysql-imagestream.yaml
  - invoice-mysql-service.yaml
  # Notification Application
  - notification-app-deploymentconfig.yaml
  - notification-app-imagestream.yaml
  # Notification Database
  - notification-mongodb-claim0-persistentvolumeclaim.yaml
  - notification-mongodb-deploymentconfig.yaml
  - notification-mongodb-imagestream.yaml
  - notification-mongodb-service.yaml  
  # JHipster Registry
  - jhipster-registry-claim0-persistentvolumeclaim.yaml
  - jhipster-registry-configmap.yaml
  - jhipster-registry-deploymentconfig.yaml
  - jhipster-registry-imagestream.yaml
  - jhipster-registry-service.yaml  
  - jhipster-registry-route.yaml
  # JHipster logstash
  - jhipster-logstash-claim0-persistentvolumeclaim.yaml
  - jhipster-logstash-deploymentconfig.yaml
  - jhipster-logstash-imagestream.yaml
  - jhipster-logstash-service.yaml
  # JHipster Console
  - jhipster-console-deploymentconfig.yaml
  - jhipster-console-imagestream.yaml
  - jhipster-console-service.yaml
  - jhipster-console-route.yaml
  # JHipster elasticsearch
  - jhipster-elasticsearch-deploymentconfig.yaml
  - jhipster-elasticsearch-imagestream.yaml
  - jhipster-elasticsearch-service.yaml
  # JHipster import Job
  - jhipster-import-dashboards-deploymentconfig.yaml
  - jhipster-import-dashboards-imagestream.yaml
