apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    com.xebialabs.service: store-app
  name: store-app
spec:
  replicas: 1
  selector:
    com.xebialabs.service: store-app
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        com.xebialabs.service: store-app
    spec:
      containers:
      - env:
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka
        - name: JHIPSTER_REGISTRY_PASSWORD
          value: admin
        - name: JHIPSTER_SLEEP
          value: "30"
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://admin:${jhipster.registry.password}@jhipster-registry:8761/config
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://store-mysql:3306/store?useUnicode=true&characterEncoding=utf8&useSSL=false
        - name: SPRING_PROFILES_ACTIVE
          value: prod,swagger
        image: ' '
        name: store-app
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - store-app
      from:
        kind: ImageStreamTag
        name: store-app:latest
    type: ImageChange